version: '3.8'

services:
  db:
    image: mysql:8.4  # Using MySQL version 8.4
    container_name: ticket_booking_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234       # Your MySQL root password
      MYSQL_DATABASE: ticket_booking  # Database name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
