{
    "swagger": "2.0",
    "info": {
      "description": "This is a sample server for a movie ticket booking system.",
      "version": "1.0",
      "title": "Ticket Booking API",
      "contact": {
        "name": "API Support",
        "url": "http://www.swagger.io/support",
        "email": "support@swagger.io"
      },
      "license": {
        "name": "Apache 2.0",
        "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
      }
    },
    "host": "localhost:8080",
    "basePath": "/",
    "paths": {
      "/register": {
        "post": {
          "summary": "Register a new user",
          "tags": ["Authentication"],
          "consumes": ["application/json"],
          "produces": ["application/json"],
          "parameters": [
            {
              "in": "body",
              "name": "user",
              "description": "User registration details",
              "required": true,
              "schema": {
                "$ref": "#/definitions/User"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "type": "object"
              }
            },
            "400": {
              "description": "Bad Request",
              "schema": {
                "type": "object"
              }
            }
          }
        }
      }
      
    }
  }
  